name: CMake

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build Type"
        required: true
        default: "Release"
        type: choice
        options:
        - Debug
        - RelWithDebInfo
        - Release

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    env:
      BUILD_TYPE: ${{ inputs.buildType }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install emsdk
      run: |
        ./third_party/emsdk/emsdk install latest

    - name: Build
      run: |
        ./third_party/emsdk/emsdk activate latest
        source ./third_party/emsdk/emsdk_env.sh
        emcmake cmake . -B ${{github.workspace}}/embuild -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/embuild --config ${{env.BUILD_TYPE}}
        cmake --install embuild --config ${{env.BUILD_TYPE}}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './dist'

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2