name: CMake

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install emsdk
      run: |
        ./third_party/emsdk/emsdk install latest

    - name: Configure CMake
      run: |
        ./third_party/emsdk/emsdk activate latest
        source ./third_party/emsdk/emsdk_env.sh
        emcmake cmake . -B ${{github.workspace}}/embuild -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/embuild --config ${{env.BUILD_TYPE}}
        cmake --install embuild --config ${{env.BUILD_TYPE}}
